#!/bin/bash


[ -x "$(command -v doas)" ] && [ -e /etc/doas.conf ] && ld="doas"
[ -x "$(command -v sudo)" ] && ld="sudo"

$ld apt install apt-transport-https curl gnupg -yy

curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | $ld apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -

echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | $ld tee /etc/apt/sources.list.d/brave-browser-release.list

$ld apt update

$ld apt install brave-browser -yy

