#!/bin/bash


# checking whether repos are cloned
# clone several repositories
echo "Cloning several repositories using git."

git clone https://github.com/brynkii/dotfiles.git ~/dotfiles
git clone https://github.com/brynkii/suckless.git ~/.config/suckless
git clone https://github.com/brynkii/backgrounds.git ~/.config/backgrounds

# repository verifier


echo "
░░░░░░  ░░░░░░░ ░░░░░░  ░░  ░░░░░  ░░░    ░░     ░░░░░░░  ░░░░░░ ░░░░░░  ░░ ░░░░░░  ░░░░░░░░ ░░░░░░░ 
▒▒   ▒▒ ▒▒      ▒▒   ▒▒ ▒▒ ▒▒   ▒▒ ▒▒▒▒   ▒▒     ▒▒      ▒▒      ▒▒   ▒▒ ▒▒ ▒▒   ▒▒    ▒▒    ▒▒      
▒▒   ▒▒ ▒▒▒▒▒   ▒▒▒▒▒▒  ▒▒ ▒▒▒▒▒▒▒ ▒▒ ▒▒  ▒▒     ▒▒▒▒▒▒▒ ▒▒      ▒▒▒▒▒▒  ▒▒ ▒▒▒▒▒▒     ▒▒    ▒▒▒▒▒▒▒ 
▓▓   ▓▓ ▓▓      ▓▓   ▓▓ ▓▓ ▓▓   ▓▓ ▓▓  ▓▓ ▓▓          ▓▓ ▓▓      ▓▓   ▓▓ ▓▓ ▓▓         ▓▓         ▓▓ 
██████  ███████ ██████  ██ ██   ██ ██   ████     ███████  ██████ ██   ██ ██ ██         ██    ███████
"

# Run the setup script
bash ~/debian-scripts/setup


# set up the tui



# set up the gui




# Setup the display manager


printf "\e[1;32mYou can now reboot! Thanks you.\e[0m\n"
