#!/bin/bash

# clone several repositories
echo "Cloning several repositories using git."

git clone https://github.com/brynkii/dotfiles.git ~/dotfiles
git clone https://github.com/brynkii/suckless.git ~/.config/suckless
git clone https://github.com/brynkii/backgrounds.git ~/.config/backgrounds

# repository verifier

clear

