#!/bin/bash

GREEN='\e[32m'
RC='\e[0m\n'
YELLOW='\e[33m'

printf "${YELLOW}Does the computer permit virtualization.${RC}"
egrep -c '(vmx|svm)' /proc/cpuinfo
sudo apt install qemu-kvm qemu-system qemu-utils python3 python3-pip libvirt-clients libvirt-daemon-system bridge-utils virtinst libvirt-daemon virt-manager -y
printf "${GREEN}QEMU has been installed.${RC}"
sudo systemctl enable libvirtd
sudo systemctl start libvirtd
sudo systemctl status libvirtd.service
printf "${YELLOW}starting libvirt.d service. Checking default network for networking.${RC}"
sudo virsh net-start default
sudo virsh net-autostart default
sudo virsh net-list --all
printf "${YELLOW}Adding user to libvirtd to allow access to VMs.${RC}"
sudo usermod -aG libvirt $USER
sudo usermod -aG libvirt-qemu $USER
sudo usermod -aG kvm $USER
sudo usermod -aG input $USER
sudo usermod -aG disk $USER
printf "${GREEN}The Process has been successful you can now reboot.${RC}"

