#!/bin/bash
# Make sure you have non-free repos enabled in /etc/apt/sources.list and run updates your system before running this script

# use doas if installed

[ -x "$(command -v doas)" ] && [ -e /etc/doas.conf ] && ld="doas"
[ -x "$(command -v sudo)" ] && ld="sudo"


$ld dpkg --add-architecture i386

$ld apt update -yy

$ld apt install steam mesa-vulkan-drivers libglx-mesa0:i386 mesa-vulkan-drivers:i386 libgl1-mesa-dri:i386 -yy

