#!/usr/bin/env bash

GREEN='\e[32m'
RC='\e[0m\n'
YELLOW='\e[33m'

printf "${YELLOW}Starting the dwm customization process${rc}"
# move autostart
mkdir -p ~/.local/share/dwm
\cp  ~/debian-scripts/resources/autostart.sh ~/.local/share/dwm/

# move original dwm build
mv ~/.config/suckless/ ~/.config/suckless.orig/

# moving patched suckless
git clone https://github.com/brynkii/suckless.git "${XDG_CONFIG_HOME:-$HOME/.config}"/suckless 

cd ~/.config/suckless/dwm
make
sudo make clean install

cd ~/.config/suckless/slstatus
make
sudo make clean install

cd ~/.config/suckless/dmenu
make
sudo make clean install

cd ~/.config/suckless/st
make
sudo make clean install

cd ~/.config/suckless/slock
make
sudo make clean install

cd ~/.config/suckless/tabbed
make
sudo make clean install

printf "${GREEN}dwm has been customized. Enjoy your new desktop.${RC}"
